/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paint;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author king
 */

public class Colora extends javax.swing.JFrame implements Node {

    /**
     * Creates new form Colora
     */
    static Color color,fcolor;
    private Node parent;
    public Colora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Border");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        color=JColorChooser.showDialog(null, "Chooser", Color.gray);
        Shapss.shapes s = null;
            Shapss.shapes c = null;
       //JOptionPane.showMessageDialog(null,shapename + shapei);
       if(Drawingapp.shapei>0)
       {
          c= (Shapss.shapes) Shapss.shapes.shape.get(Drawingapp.shapei-1);
         // JOptionPane.showMessageDialog(null,"10"+shapename + shapei);
         //while(true){
         // String cen=JOptionPane.showInputDialog(null, "Enter color (color,fcolor)");
          //String[] cir=cen.split(",");
          //color=this.getColor(cir[0]);
          //fcolor=this.getColor(cir[1]);
           //if((color instanceof Color)&&(fcolor instanceof Color))
           //break;
           //else
            //JOptionPane.showMessageDialog(null,"Entr again ");
           
         //}
         
          c.setColor(Colora.color, c.getFillColor(), Drawingapp.shapei-1 );
          
        }
         
         
      if(Shapss.shapes.shape.size()>0)
      {
          s=(Shapss.shapes) Shapss.shapes.shape.get(0);
          s.refresh(Drawingapp.g);
          //JOptionPane.showMessageDialog(null, "Enter point2 (x2,y2)");
      } 
      this.dispose();
         ((Drawingapp) getparentNode()).setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fcolor=JColorChooser.showDialog(null, "Chooser", Color.gray);
         Shapss.shapes s = null;
            Shapss.shapes c = null;
       //JOptionPane.showMessageDialog(null,shapename + shapei);
       if(Drawingapp.shapei>0)
       {
          c= (Shapss.shapes) Shapss.shapes.shape.get(Drawingapp.shapei-1);
         // JOptionPane.showMessageDialog(null,"10"+shapename + shapei);
         //while(true){
         // String cen=JOptionPane.showInputDialog(null, "Enter color (color,fcolor)");
          //String[] cir=cen.split(",");
          //color=this.getColor(cir[0]);
          //fcolor=this.getColor(cir[1]);
           //if((color instanceof Color)&&(fcolor instanceof Color))
           //break;
           //else
            //JOptionPane.showMessageDialog(null,"Entr again ");
           
         //}
         
          c.setColor(c.getColor(), Colora.fcolor, Drawingapp.shapei-1 );
          
        }
         
         
      if(Shapss.shapes.shape.size()>0)
      {
          s=(Shapss.shapes) Shapss.shapes.shape.get(0);
          s.refresh(Drawingapp.g);
          //JOptionPane.showMessageDialog(null, "Enter point2 (x2,y2)");
      } 
      this.dispose();
         ((Drawingapp) getparentNode()).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

  @Override
    public Node getparentNode() {
        return parent;
    }

    @Override
    public void setparentNode(Node node) {
        
       this.parent=node;
    }
}
